import json
ckpt = json.load(open(".funnel_checkpoint.json"))
prices = ckpt.get("price_cache", {})
mimo = ckpt.get("mimo_results", {})
for t in ["MSFT","ACN","NKE","ICE","MCD","ATO","CLX","SYK","ABT"]:
    p = prices.get(t, {})
    m = mimo.get(t, {})
    dd = p.get("pct_below_52w_high", "N/A")
    rsi = p.get("rsi_14", "N/A")
    cw = p.get("current_yield", "N/A")
    ay = p.get("avg_yield_5yr", "N/A")
    er = p.get("yield_expansion_ratio", "N/A")
    pt = p.get("price_trend", "N/A")
    dq = p.get("data_quality", "N/A")
    print(f"{t:6s}  dd={dd}  rsi={rsi}  cur_yld={cw}  avg_yld={ay}  yld_exp={er}  trend={pt}  dq={dq}")
